name: animated_native_splash
description: A package which automates the task of creating an animated splash
  screen in a flutter.
version: 1.3.0
homepage: https://github.com/Rexfordasamoah51/flutter_animated_splash_screen
maintainer: Rexford Asamoah

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  args: ^2.4.2
  image: ^4.1.7
  meta: ^1.10.0
  path: ^1.8.3
  xml: ^6.5.0
  yaml: ^3.1.2
  universal_io: ^2.2.2
  

dev_dependencies: 
  flutter_lints: ^3.0.1
